### ISSUE TITLE
Does an installation on Windows require uninstalling Python versions other than 2.7 beforehand?

### ISSUE THREAD

**Issue by mpatca** [novoid/tagstore#1]
I am not sure if the question fits in here, but the answer might be interesting for others. The old tagstore website says that installation on Windows may require prior uninstallation of Python versions other than 2.7.: Is this really necessary, or could I simply install Python 2.7 or use the Windows installation file if Python 3.x is already installed?

If I try to install it manually on Windows, I get an error message when I start tagstore_manager.py. Python 3.11 is installed, so would I have to uninstall 3.11, then install tagstore (including Python 2.7) and then install 3.11 again?

**Comment by novoid** [comment]
Hi @mpatca,

Thanks for the question.

It's been a while since I took a look at the research framework tagstore because I'm using [a different method in my private life](https://karl-voit.at/managing-digital-photographs/).

Somehow, there is no requirements.txt defining the requirements. That's bad habbit. Sorry for that.

When I take a look at https://github.com/novoid/tagstore/blob/master/tagstore.py it states `#!/usr/bin/env python` which - I guess - lets the OS decide which Python version to use if Python 2 and 3 are installed in parallel.

The Readme mentions Python 2 in an example so I'm afraid that tagstore never got migrated to Python 3 and I don't know how much effort this requires. You can try to apply 2to3 to all py-files and see if that helps without further manual fixes.

If you do have Python 2 and you want to make sure that tagstore is using Python 2, you can change all shebangs of all py-files from `#!/usr/bin/env python` to `#!/usr/bin/env python2`. That should do fine without much changes.

I don't know the answer to your original question: if you'd need to uninstall a Python version on Windows before using tagstore. If so, you'd need to uninstall Python 3 which would be a shame since Python 2 is depricated in the meantime.

I'm closing that issue for the moment - you might continue posting your experience here.
